### ISSUE TITLE
Improve ICD test reliability: region manipulation

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#189]
1.
The final two sub-tests of `src/test/REGION_REGISTER.test.ts` seem to fail despite the test passing overall

```
        Modify region #3
          ✕ SET_REGION_ACK should return within 500 ms (33ms)
          ✕ SET_REGION_ACK.success = false (2ms)

```
```

  ● REGION_REGISTER: Testing region creation and modification › Go to "set_QA" folder and open image "M17_SWex.fits" to set image view › Remove region #3 › Modify region #3 › SET_REGION_ACK should return within 500 ms
    Failed: Object {
      "message": "Region 3 parameters for file 0 failed",
      "tags": Array [
        "region",
      ],
    }
      222 |             describe("Modify region #3", () => {
      223 |                 let SetRegionAck: CARTA.SetRegionAck;
    > 224 |                 test(`SET_REGION_ACK should return within ${regionTimeout} ms`, async () => {
          |                 ^
      225 |                     await Connection.send(CARTA.SetRegion,
      226 |                         {
      227 |                             fileId: 0,
      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.describe (src/test/REGION_REGISTER.test.ts:224:17)
      at Suite.describe (src/test/REGION_REGISTER.test.ts:222:13)

  ● REGION_REGISTER: Testing region creation and modification › Go to "set_QA" folder and open image "M17_SWex.fits" to set image view › Remove region #3 › Modify region #3 › SET_REGION_ACK.success = false
    TypeError: Cannot read property 'success' of undefined
      239 |
      240 |                 test("SET_REGION_ACK.success = false", () => {
    > 241 |                     expect(SetRegionAck.success).toBe(false);
          |                                         ^
      242 |                 });
      243 |
      244 |             });
      at Object.test (src/test/REGION_REGISTER.test.ts:241:41)
  console.warn src/test/CLIENT.ts:188
    Region 3 parameters for file 0 failed
```

2.
In `src/test/CASA_REGION_IMPORT_EXPORT.test.ts` one import fails:

      Import "M17_SWex_testRegions_pix.crtf"
        ✕ IMPORT_REGION_ACK should return within 500ms (51ms)
        ✕ IMPORT_REGION_ACK.success = true (1ms)
        ✕ Length of IMPORT_REGION_ACK.region = 7
        ✕ IMPORT_REGION_ACK.region[0] = "Id:1, Type:RECTANGLE"
        ✕ IMPORT_REGION_ACK.region[1] = "Id:2, Type:RECTANGLE"
        ✕ IMPORT_REGION_ACK.region[2] = "Id:3, Type:RECTANGLE"
        ✕ IMPORT_REGION_ACK.region[3] = "Id:4, Type:POLYGON"
        ✕ IMPORT_REGION_ACK.region[4] = "Id:5, Type:ELLIPSE" (1ms)
        ✕ IMPORT_REGION_ACK.region[5] = "Id:6, Type:ELLIPSE"
        ✕ IMPORT_REGION_ACK.region[6] = "Id:7, Type:POINT"

The file **does** exist in `set_QA/set_QA_regionTest/M17_SWex_testRegions_pix.crtf` and the other crtf files in the test get imported without issues. Could this be the problem?

```
    Failed: Object {
      "message": " Region type annulus is not supported yet.
     Region type line is not supported yet.
    ",
```

3.
In `src/test/CASA_REGION_IMPORT_EXCEPTION.test.ts` all tests fail:

```
      Import "M17_SWex_regionSet2_pix.crtf"
        ✕ IMPORT_REGION_ACK should return within 500ms (47ms)
        ✕ IMPORT_REGION_ACK.success = false
        ✕ IMPORT_REGION_ACK.message should not be empty (1ms)
      Import "M17_SWex_regionSet2_world.crtf"
        ✕ IMPORT_REGION_ACK should return within 500ms (21ms)
        ✕ IMPORT_REGION_ACK.success = false
        ✕ IMPORT_REGION_ACK.message should not be empty (1ms)
```

Could this be the problem?

```

    Failed: Object {
      "message": "/almalustre/carta/images/set_QA/set_QA_regionTest/M17_SWex_regionSet2_pix.crtf line# 2: _init: Mixed world and pixel coordinates not supported ",
      "severity": "ERROR",
      "tags": Array [
        "import",
```

**Comment by zarda** [comment]
Thanks for the bug reports. The tests are updated.
